name: Check for outdated dependencies

on:
  push:
    branches: [ main ]
  pull_request:
  schedule:
    - cron: '0 0 * * *' # Run daily

jobs:
  outdated:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install cargo-outdated
        run: cargo install cargo-outdated
      - name: Run outdated
        run: cargo outdated
